spring:
  application:
    name: ecom-demo

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres@123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true

  # mail:
  #   host: sandbox.smtp.mailtrap.io
  #   port: 2525
  #   username: 3210de6d30d855
  #   password: 69014a644841e4
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true

server:
  port: 9090
# jwt:
#   secret: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N9dPip32yQynt59595E
#   expiration: 86400000

# -----------------------------------------------------
########### Default settings
# services:
#   mysql:
#     image: 'mysql:latest'
#     environment:
#       - 'MYSQL_DATABASE=mydatabase'
#       - 'MYSQL_PASSWORD=secret'
#       - 'MYSQL_ROOT_PASSWORD=verysecret'
#       - 'MYSQL_USER=myuser'
#     ports:
#       - '3306'
#   postgres:
#     image: 'postgres:latest'
#     environment:
#       - 'POSTGRES_DB=mydatabase'
#       - 'POSTGRES_PASSWORD=secret'
#       - 'POSTGRES_USER=myuser'
#     ports:
#       - '5432'
