services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=mydatabase"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=myuser"
    ports:
      - "3306:3306"
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5432:5432"
# ---------------------------------------
# version: '3.8'

# services:
#   database:
#     image: postgres:latest
#     container_name: postgres_db
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#     ports:
#       - "5432:5432"

#   app:
#     image: your_spring_boot_app_image:latest
#     container_name: spring_boot_app
#     depends_on:
#       - database
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/mydatabase
#       SPRING_DATASOURCE_USERNAME: myuser
#       SPRING_DATASOURCE_PASSWORD: mypassword
#     ports:
#       - "9090:9090"
